---
title: "Interesting Forecasting Applications with R"
author: Umit Baris Gokkaya - IE360 - Fall 2020
---
```{r,echo=FALSE,results="hide"}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

1. [Time series forecasting using ARIMA models](https://blogs.oracle.com/datascience/introduction-to-forecasting-with-arima-in-r)

    This example is important because it introduces the forecasting methodology using ARIMA models in R. The steps are:
    1) Examine your data
    2) Decompose your data
    3) Stationarity
    4) Autocorrelations and choosing model order
    5) Fit an ARIMA model
    6) Evaluate and iterate


2. [Sales forecasting](https://www.skyword.com/marketing-dictionary/sales-forecasting/)
    
    Sales forecasting is predicting future sales of a company. This may help with making better short and long-term decisions. Companies can use these predictions to optimally manage workforce and cash flow.
    
    Sales forecasting can be based on past sales data and market movements.
  

3. [Census Analysis](https://en.wikipedia.org/wiki/Demographic_analysis)
  
    Census analysis may be used by government agencies to better plan public works. Forecasting future census counts can be beneficial for preventing diseases, housing and food crises, etc.
  
4. [Meteorology](https://en.wikipedia.org/wiki/Meteorology)

    Perhaps the most common application of statistical forecasting, meteorologists use past weather and climate data to predict the weather of a region at a given time.
    
    Weather forecasts are based on many factors such as temperature, air pressure, precipitation. Predictions can be used by utility providers to further predict energy usage, economists to predict the market prices.
  
  
5. [Energy forecasting](https://en.wikipedia.org/wiki/Energy_forecasting)
    
    Energy forecasting is the prediction of future energy needs at both local and global level. Energy forecasting models take into account historical trends, weather inputs, tariff structures and occupancy schedules to make predictions. 
    
    Especially in an era where we are running out of fossil fuels, developing alternate methods is crucial.
